


  - name: Create (or update) PostgreSQL Database
    azure_rm_postgresqldatabase:
      resource_group: "{{tf_app_env_outputs.postgres_resource_group_name.value}}"
      server_name: "{{ tf_app_env_outputs.atat_database_instance_name.value }}"
      name: "{{ tf_app_env_outputs.pg_server_name.value }}"
      secret: "{{ lookup('env','SUBSCRIPTION_SECRET') }}"
      client_id: "{{ lookup('env','SUBSCRIPTION_CID') }}"
      subscription_id: "{{ lookup('env','SUBSCRIPTION_ID')}}"
      tenant: "{{ lookup('env','SUBSCRIPTION_TENANT')}}"


  - name: install poetry deps
    shell:
      cmd: poetry install
      chdir: /Users/michaelpapetti/Developer/atst

  - name: Create database user
    shell:
      cmd:   script/create_database_user.py "{{ tf_app_env_outputs.atat_user_name.value }}" "{{ tf_app_env_outputs.atat_user_password.value }}"
      chdir: /src
    environment:
       PGDATABASE: "atat"
       SERVER_NAME: "{{ tf_app_env_outputs.atat_database_instance_name.value }}"
       SERVER_GROUP: "{{ tf_app_env_outputs.postgres_resource_group_name.value }}"
       SERVER_ADMIN_NAME: "{{ tf_app_env_outputs.postgres_root_user_name.value }}"
       PGUSER: "{{ tf_app_env_outputs.postgres_root_user_name.value  }}"
       PGPASSWORD: "{{  tf_app_env_outputs.postgres_root_password.value  }}"
       PGHOST: "{{ tf_app_env_outputs.pg_host.value }}"
       ATAT_PGUSER: "{{ tf_app_env_outputs.atat_user_name.value }}"
       ATAT_PGPASSWORD: "{{  tf_app_env_outputs.atat_user_password.value  }}"
       PGDATABASE: "atat"

  - name: Initialize database
    script: "poetry run script/reset_database.py"
    args:
      chdir: /src
    environment:
        PGDATABASE: "atat"
        SERVER_NAME: "{{ tf_app_env_outputs.atat_database_instance_name.value }}"
        SERVER_GROUP: "{{ tf_app_env_outputs.postgres_resource_group_name.value }}"
        SERVER_ADMIN_NAME: "{{ tf_app_env_outputs.postgres_root_user_name.value }}"
        PGUSER: "{{ tf_app_env_outputs.postgres_root_user_name.value  }}"
        PGPASSWORD: "{{  tf_app_env_outputs.postgres_root_password.value  }}"
        PGHOST: "{{ tf_app_env_outputs.pg_host.value }}"

  - name: Add CCPO users
    script: "script/add_ccpo_users.py script/users.yml"
    args:
      chdir: /src
    environment:
        PGDATABASE: "atat"
        SERVER_NAME: "{{ tf_app_env_outputs.atat_database_instance_name.value }}"
        SERVER_GROUP: "{{ tf_app_env_outputs.postgres_resource_group_name.value }}"
        SERVER_ADMIN_NAME: "{{ tf_app_env_outputs.postgres_root_user_name.value }}"
        PGUSER: "{{ tf_app_env_outputs.postgres_root_user_name.value  }}"
        PGPASSWORD: "{{  tf_app_env_outputs.postgres_root_password.value  }}"
        PGHOST: "{{ tf_app_env_outputs.pg_host.value }}"
