- name: make k/v
  set_fact:
    kv_tf: "{{ kv_tf|default({}) | combine({ item : (secrets_env[item] | regex_replace(\"'\",'\"'))  }) }}"
  with_items: "{{ secrets_env }}"

- name: show_kv_tf
  debug:
    msg: "{{ kv_tf }}"
