







- name: "Create secret"
  azure_rm_keyvaultsecret:
    subscription_id: "{{ vault_subscription_id }}"
    secret: "{{ vault_secret }}"
    client_id: "{{  vault_client_id  }}"
    tenant: "{{ vault_tenant }}"
    secret_name: "{{ item }}"
    secret_value: "{{ vars_vals[item] }}"
    keyvault_uri: "{{ vault_url }}"
    tags:
      deploy_tag: "{{deploy_tag}}"
  with_items: "{{ vars_vals }}"
