







- name: "Create secret"
  azure_rm_keyvaultsecret:
    subscription_id: "{{ vault_subscription_id }}"
    secret: "{{ vault_secret }}"
    client_id: "{{  vault_client_id  }}"
    tenant: "{{ vault_tenant }}"
    secret_name: "{{ item }}"
    secret_value: "{{ top_level_app_vals[item] }}"
    keyvault_uri: "{{ app_vault_url }}"
    tags:
      deploy_tag: "{{deploy_tag}}"
  with_items: "{{ top_level_app_vals }}"
