

- name: pickup application_env variables
  set_fact:
    app_vars_vals: "{{ lookup('to_hcl', tf_base_dir ~ '/application_env' ~ '/app.tfvars.json' ) | safe | string }}"



- include: ../../bootstrap/tasks/show_outputs.yml


- name: get app _output
  include: ../../terraform/tasks/get_backend.yml

- include: ../../terraform/tasks/show_outputs.yml




- name: "show outputs of app_config_values"
  debug:
    msg:  " outputs are .. {{ tf_app_env_outputs.app_config_values.value }}"

- name: set var values fact
  set_fact:
    top_level_app_vals: '{{ tf_app_env_outputs.app_config_values.value | safe | string |  regex_replace("''",''"'')  | from_json }}'
