

- name: get secrets
  vars:
    url:  "{{ vault_url }}"
    ops_keyvault_client_id: "{{ vault_client_id }}"
    ops_keyvault_secret:    "{{ vault_secret }}"
    ops_keyvault_tenant:  "{{ vault_tenant }}"
    secretname: "{{ deploy_tag | regex_replace('\\.','-') }}"
  set_fact:
    secrets_env: "{{ secrets_env|default({})   | combine( { deploy_tag:  (lookup('azure_keyvault_list_secrets',secretname, vault_url=url, client_id=ops_keyvault_client_id, secret=ops_keyvault_secret, tenant_id=ops_keyvault_tenant) | regex_replace('\"','') | regex_replace(\"'\",'\"') | regex_replace('\\[\\{','{') | regex_replace('\\}\\]','}') ) } ) }}"


- name: delete all secrets in list
  azure_rm_keyvaultsecret:
    client_id: "{{ vault_client_id }}"
    tenant: "{{vault_tenant}}"
    secret: "{{vault_secret}}"
    subscription_id: "{{ vault_subscription_id}}"
    secret_name:  "{{item}}"
    state: "absent"
    keyvault_uri: "{{vault_url}}"
  with_items: "{{ secrets_env }}"
