---

init_tf: yes
deploy_app_env: true
show_app_env_outputs: true
tf_base_dir: /src/terraform/providers
tf_subdir: application_env
tfvars_file_name: app.tfvars.json
application_subscription_id: "{{ lookup('env','SUBSCRIPTION_ID') }}"
terraform_dir: "{{ tf_dir }}"
terraform_deploy_version: "{{ deploy_tag }}"
keyvault_list_service_principle_client_id: "{{ vault_client_id }}"
keyvault_list_service_principle_secret:    "{{ vault_secret }}"
keyvault_list_service_principle_tenant:  "{{ vault_tenant }}"
bs_client_id: "{{ lookup('env','TF_VAR_OPS_CID') }}"
bs_tenant: "{{ lookup('env','AZURE_TENANT_ID') }}"
bs_secret: "{{ lookup('env','TF_VAR_OPS_SEC') }}"
boostrap_resource_group_name: cloudzero-ops
bootstrap_storage_account_name: czopsstorageaccount
bootstrap_container_name: tf-configs
bootstrap_subscription_id: "{{ lookup('env','SUBSCRIPTION_ID') }}"
