apiVersion: apps/v1
kind: Deployment
metadata:
  name: atst
spec:
  template:
    spec:
      volumes:
        - name: nginx-secret
          flexVolume:
            options:
              usepodidentity: "false"
              usevmmanagedidentity: "true"
              vmmanagedidentityclientid: $VMSS_CLIENT_ID
              keyvaultname: "cz-{{ namespace }}-keyvault"
              keyvaultobjectnames: "dhparam4096;atatdev;atatdev"
        - name: flask-secret
          flexVolume:
            options:
              usepodidentity: "false"
              usevmmanagedidentity: "true"
              vmmanagedidentityclientid: $VMSS_CLIENT_ID
              keyvaultname: "cz-{{ namespace }}-keyvault"
              keyvaultobjectnames: "AZURE-STORAGE-KEY;MAIL-PASSWORD;PGPASSWORD;REDIS-PASSWORD;SECRET-KEY;AZURE-TENANT-ID;AZURE-CLIENT-ID;AZURE-USER-OBJECT-ID;AZURE-TENANT-ADMIN-PASSWORD;AZURE-SECRET-KEY;AZURE-HYBRID-TENANT-ID;AZURE-BILLING-ACCOUNT-NAME;AZURE-BILLING-PROFILE-ID;AZURE-INVOICE-SECTION-ID;AZURE-HYBRID-REPORTING-CLIENT-ID;AZURE-HYBRID-REPORTING-SECRET"
              keyvaultobjectaliases: "AZURE_STORAGE_KEY;MAIL_PASSWORD;PGPASSWORD;REDIS_PASSWORD;SECRET_KEY;AZURE_TENANT_ID;AZURE_CLIENT_ID;AZURE_USER_OBJECT_ID;AZURE_TENANT_ADMIN_PASSWORD;AZURE_SECRET_KEY;AZURE_HYBRID_TENANT_ID;AZURE_BILLING_ACCOUNT_NAME;AZURE_BILLING_PROFILE_ID;AZURE_INVOICE_SECTION_ID;AZURE_HYBRID_REPORTING_CLIENT_ID;AZURE_HYBRID_REPORTING_SECRET"
              keyvaultobjecttypes: "secret;secret;secret;secret;key;secret;secret;secret;secret;secret;secret;secret;secret;secret;secret;secret"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atst-worker
spec:
  template:
    spec:
      volumes:
        - name: flask-secret
          flexVolume:
            options:
              usepodidentity: "false"
              usevmmanagedidentity: "true"
              vmmanagedidentityclientid: $VMSS_CLIENT_ID
              keyvaultname: "cz-{{ namespace }}-keyvault"
              keyvaultobjectnames: "AZURE-STORAGE-KEY;MAIL-PASSWORD;PGPASSWORD;REDIS-PASSWORD;SECRET-KEY;AZURE-TENANT-ID;AZURE-CLIENT-ID;AZURE-USER-OBJECT-ID;AZURE-TENANT-ADMIN-PASSWORD;AZURE-SECRET-KEY;AZURE-HYBRID-TENANT-ID"
              keyvaultobjectaliases: "AZURE_STORAGE_KEY;MAIL_PASSWORD;PGPASSWORD;REDIS_PASSWORD;SECRET_KEY;AZURE_TENANT_ID;AZURE_CLIENT_ID;AZURE_USER_OBJECT_ID;AZURE_TENANT_ADMIN_PASSWORD;AZURE_SECRET_KEY;AZURE_HYBRID_TENANT_ID"
              keyvaultobjecttypes: "secret;secret;secret;secret;key;secret;secret;secret;secret;secret;secret"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atst-beat
spec:
  template:
    spec:
      volumes:
        - name: flask-secret
          flexVolume:
            options:
              usepodidentity: "false"
              usevmmanagedidentity: "true"
              vmmanagedidentityclientid: $VMSS_CLIENT_ID
              keyvaultname: "cz-{{ namespace }}-keyvault"
              keyvaultobjectnames: "AZURE-STORAGE-KEY;MAIL-PASSWORD;PGPASSWORD;REDIS-PASSWORD;SECRET-KEY;AZURE-TENANT-ID;AZURE-CLIENT-ID;AZURE-USER-OBJECT-ID;AZURE-TENANT-ADMIN-PASSWORD;AZURE-SECRET-KEY;AZURE-HYBRID-TENANT-ID"
              keyvaultobjectaliases: "AZURE_STORAGE_KEY;MAIL_PASSWORD;PGPASSWORD;REDIS_PASSWORD;SECRET_KEY;AZURE_TENANT_ID;AZURE_CLIENT_ID;AZURE_USER_OBJECT_ID;AZURE_TENANT_ADMIN_PASSWORD;AZURE_SECRET_KEY;AZURE_HYBRID_TENANT_ID"
              keyvaultobjecttypes: "secret;secret;secret;secret;key;secret;secret;secret;secret;secret;secret"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crls
spec:
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: flask-secret
              flexVolume:
                options:
                  usepodidentity: "false"
                  usevmmanagedidentity: "true"
                  vmmanagedidentityclientid: $VMSS_CLIENT_ID
                  keyvaultname: "cz-{{ namespace }}-keyvault"
                  keyvaultobjectnames: "AZURE-STORAGE-KEY;MAIL-PASSWORD;PGPASSWORD;REDIS-PASSWORD;SECRET-KEY;AZURE-TENANT-ID;AZURE-CLIENT-ID;AZURE-USER-OBJECT-ID;AZURE-TENANT-ADMIN-PASSWORD;AZURE-SECRET-KEY;AZURE-HYBRID-TENANT-ID"
                  keyvaultobjectaliases: "AZURE_STORAGE_KEY;MAIL_PASSWORD;PGPASSWORD;REDIS_PASSWORD;SECRET_KEY;AZURE_TENANT_ID;AZURE_CLIENT_ID;AZURE_USER_OBJECT_ID;AZURE_TENANT_ADMIN_PASSWORD;AZURE_SECRET_KEY;AZURE_HYBRID_TENANT_ID"
                  keyvaultobjecttypes: "secret;secret;secret;secret;key;secret;secret;secret;secret;secret;secret"
