---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-worker-envvars
data:
  CAC_URL: https://auth-master.atat.dev/login-redirect
  CELERY_DEFAULT_QUEUE: celery-master
  FLASK_ENV: master
  PGDATABASE: cloudzero_dryrun_master
  SERVER_NAME: master.atat.dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-envvars
data:
  CAC_URL: https://auth-master.atat.dev/login-redirect
  CDN_ORIGIN: https://master.atat.dev
  CELERY_DEFAULT_QUEUE: celery-master
  FLASK_ENV: master
  PGDATABASE: cloudzero_dryrun_master
  STATIC_URL: "https://master.atat.dev/static/"
  SAML_ENTITY_ID: https://master.atat.dev/login-dev
  SAML_ACS: https://master.atat.dev/login-dev?acs
  SAML_SLS: https://master.atat.dev/login-dev?sls
  SAML_IDP_ENTITY_ID: https://sts.windows.net/b5ab0e1e-09f8-4258-afb7-fb17654bc5b3/
  SAML_IDP_SSOS: https://login.microsoftonline.com/b5ab0e1e-09f8-4258-afb7-fb17654bc5b3/saml2
  SAML_IDP_SLS: https://login.microsoftonline.com/common/wsfederation?wa=wsignout1.0
  SAML_LOGIN_DEV: "true"
