token_source_tf: true
ops_registy: cloudzeroopsregistry
container_registry: "{{tf_bootstrap_backend_outputs.ops_container_registry_name.value}}"
build_and_push_ops_image: false
build_and_push_app_images: false
circle_ci_project: github/dod-ccpo/atst
