---
apiVersion: v1
kind: Service
metadata:
  name: atst-main
  annotations:
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "cloudzero-pwdev-public"
spec:
  loadBalancerIP: ""
  ports:
  - port: 80
    targetPort: 8342
    name: http
  - port: 443
    targetPort: 8442
    name: https
---
apiVersion: v1
kind: Service
metadata:
  name: atst-auth
  annotations:
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "cloudzero-pwdev-public"
spec:
  loadBalancerIP: ""
  ports:
  - port: 80
    targetPort: 8343
    name: http
  - port: 443
    targetPort: 8443
    name: https
