---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-worker-envvars
data:
  AZURE_ACCOUNT_NAME: dryrun2tasks # TODO(heyzoos) Parameterize from terraform!
  AZURE_POWERSHELL_CLIENT_ID: 1950a258-227b-4e31-a9cf-717495945fc2
  AZURE_TENANT_ADMIN_USERNAME: hybrid.admin@atathybrid.onmicrosoft.com
  AZURE_VAULT_URL: "https://tenants-dryrun2-keyvault.vault.azure.net/" # TODO(heyzoos) Parameterize from terraform!
  CELERY_DEFAULT_QUEUE: celery-staging
  CSP: hybrid
  FLASK_ENV: staging
  PGDATABASE: cloudzero_dryrun2_staging # TODO(heyzoos) Parameterize from terraform!
  PGHOST: cloudzero-dryrun2-sql.postgres.database.azure.com # TODO(heyzoos) Parameterize from terraform!
  PGUSER: atat@cloudzero-dryrun2-sql # TODO(heyzoos) Parameterize from terraform!
  PGSSLMODE: require
  REDIS_HOST: cloudzero-dryrun2-redis.redis.cache.windows.net:6380 # TODO(heyzoos) Parameterize from terraform!
  SERVER_NAME: staging.atat.dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-envvars
data:
  ASSETS_URL: ""
  AZURE_ACCOUNT_NAME: dryrun2tasks # TODO(heyzoos) Parameterize from terraform!
  AZURE_POWERSHELL_CLIENT_ID: 1950a258-227b-4e31-a9cf-717495945fc2
  AZURE_TENANT_ADMIN_USERNAME: hybrid.admin@atathybrid.onmicrosoft.com
  AZURE_VAULT_URL: "https://tenants-dryrun2-keyvault.vault.azure.net/" # TODO(heyzoos) Parameterize from terraform!
  BLOB_STORAGE_URL: https://dryrun2tasks.blob.core.windows.net/ # TODO(heyzoos) Parameterize from terraform!
  CAC_URL: https://auth-staging.atat.dev/login-redirect
  CDN_ORIGIN: https://staging.atat.dev
  CELERY_DEFAULT_QUEUE: celery-staging
  CSP: hybrid
  FLASK_ENV: staging
  PGDATABASE: cloudzero_dryrun2_staging # TODO(heyzoos) Parameterize from terraform!
  PGHOST: cloudzero-dryrun2-sql.postgres.database.azure.com # TODO(heyzoos) Parameterize from terraform!
  PGUSER: atat@cloudzero-dryrun2-sql # TODO(heyzoos) Parameterize from terraform!
  PGSSLMODE: require
  REDIS_HOST: cloudzero-dryrun2-redis.redis.cache.windows.net:6380 # TODO(heyzoos) Parameterize from terraform!
  SESSION_COOKIE_DOMAIN: atat.dev
  STATIC_URL: "https://staging.atat.dev/static/"
