---

- name: create k8s overlays
  import_tasks: generate_overlay_vars.yml

- name: create k8s overlays
  import_tasks: generate_overlays.yml
  when: private_cluster_deploy == false


- name: push overlays to storage bucket
  import_tasks: push_overlays.yml
  when: private_cluster_deploy == false


- name: configure the cluster ## eventuall will go away
  import_tasks: configure_public_cluster.yml
  when: private_cluster_deploy == false

- name: configure the private cluster
  import_tasks: configure_private_cluster.yml
  when: private_cluster_deploy == true
