apiVersion: "secrets-store.csi.x-k8s.io/v1alpha1"
kind: SecretProviderClass
metadata:
  name: atat-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    useVMManagedIdentity: "true"
    cloudName: "AzurePublicCloud"          # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: AZURE-STORAGE-KEY
          objectAlias: AZURE_STORAGE_KEY
          objectType: secret
        - |
          objectName: MAILGUN-SMTP-PASSWORD
          objectAlias: MAIL_PASSWORD
          objectType: secret
        - |
          objectName: PGPASSWORD
          objectAlias: PGPASSWORD
          objectType: secret
        - |
          objectName: REDIS-PASSWORD
          objectAlias: REDIS_PASSWORD
          objectType: secret
        - |
          objectName: SECRET-KEY
          objectAlias: SECRET_KEY
          objectType: key
        - |
          objectName: AZURE-TENANT-ID
          objectAlias: AZURE_TENANT_ID
          objectType: secret
        - |
          objectName: AZURE-CLIENT-ID
          objectAlias: AZURE_CLIENT_ID
          objectType: secret
        - |
          objectName: AZURE-USER-OBJECT-ID
          objectAlias: AZURE_USER_OBJECT_ID
          objectType: secret
        - |
          objectName: AZURE-HYBRID-TENANT-ADMIN-PASSWORD
          objectAlias: AZURE_TENANT_ADMIN_PASSWORD
          objectType: secret
        - |
          objectName: AZURE-SECRET-KEY
          objectAlias: AZURE_SECRET_KEY
          objectType: secret
        - |
          objectName: AZURE-HYBRID-TENANT-ID
          objectAlias: AZURE_HYBRID_TENANT_ID
          objectType: secret
        - |
          objectName: AZURE-BILLING-ACCOUNT-NAME
          objectAlias: AZURE_BILLING_ACCOUNT_NAME
          objectType: secret
        - |
          objectName: AZURE-BILLING-PROFILE-ID
          objectAlias: AZURE_BILLING_PROFILE_ID
          objectType: secret
        - |
          objectName: AZURE-INVOICE-SECTION-ID
          objectAlias: AZURE_INVOICE_SECTION_ID
          objectType: secret
        - |
          objectName: AZURE-HYBRID-REPORTING-CLIENT-ID
          objectAlias: AZURE_HYBRID_REPORTING_CLIENT_ID
          objectType: secret
        - |
          objectName: AZURE-HYBRID-REPORTING-SECRET
          objectAlias: AZURE_HYBRID_REPORTING_SECRET
          objectType: secret

---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: nginx-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    useVMManagedIdentity: "true"
    cloudName: "AzurePublicCloud"          # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: DHPARAMS
          objectAlias: dhparam.pem
          objectType: secret
          objectFormat: pem
        - |
          objectName: atatdev
          objectAlias: atat.key
          objectType: secret
          objectFormat: pem
        - |
          objectName: atatdev
          objectAlias: atat.crt
          objectType: secret
          objectFormat: pem

